print("==============================")
raio = float(input("Digite o raio do círculo: "))
area = 3.14159 * (raio ** 2)
print("A área do círculo com raio " + str(raio) + " é " + str(area))
print("==============================")
