print("==============================")
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
media = (nota1 * 0.5) + (nota2 * 0.5)
print("==============================")
print("Sua média é: " + str(media))
print("==============================")
