print("==============================")
a = float(input("Informe o valor de A: "))
b = float(input("Informe o valor de B: "))
c = float(input("Informe o valor de C: "))
d = float(input("Informe o valor de D: "))
e = float(input("Informe o valor de E: "))
f = float(input("Informe o valor de F: "))
x = ((c*e) - (b*f))/((a*e) - (b*d))
y = ((a*f) - (c*d))/((a*e) - (b*d))
print("O resulta de x é " + str(round(x, 2)) + " e de y é" + str(round(y, 2)))
print("==============================")