print("==============================")
notaTCC = float(input("Digite a nota do TCC: "))
notaProva = float(input("Digite a nota da prova: "))
notaTrabalho = float(input("Digite a nota do trabalho: "))
media = (notaTCC * 0.3) + (notaProva * 0.5) + (notaTrabalho * 0.2)
print("==============================")
print("Sua média é " + str(media))
print("==============================")
